require 'rails_helper'

feature 'user visit home' do
  scenario 'and view last 10 check in' do
    beer = create(:beer)
    bar0 = create(:bar, name: 'Meu Bar 0')
    bar1 = create(:bar, name: 'Meu Bar 1')
    bar2 = create(:bar, name: 'Meu Bar 2')
    bar3 = create(:bar, name: 'Meu Bar 3')
    bar4 = create(:bar, name: 'Meu Bar 4')
    bar5 = create(:bar, name: 'Meu Bar 5')
    bar6 = create(:bar, name: 'Meu Bar 6')
    bar7 = create(:bar, name: 'Meu Bar 7')
    bar8 = create(:bar, name: 'Meu Bar 8')
    bar9 = create(:bar, name: 'Meu Bar 9')
    BarBeer.create(bar: bar0, beer: beer)
    BarBeer.create(bar: bar1, beer: beer)
    BarBeer.create(bar: bar2, beer: beer)
    BarBeer.create(bar: bar3, beer: beer)
    BarBeer.create(bar: bar4, beer: beer)
    BarBeer.create(bar: bar5, beer: beer)
    BarBeer.create(bar: bar6, beer: beer)
    BarBeer.create(bar: bar7, beer: beer)
    BarBeer.create(bar: bar8, beer: beer)
    BarBeer.create(bar: bar9, beer: beer)
    Checkin.create(bar: bar0, beer: beer)
    Checkin.create(bar: bar1, beer: beer)
    Checkin.create(bar: bar2, beer: beer)
    Checkin.create(bar: bar3, beer: beer)
    Checkin.create(bar: bar4, beer: beer)
    Checkin.create(bar: bar5, beer: beer)
    Checkin.create(bar: bar6, beer: beer)
    Checkin.create(bar: bar7, beer: beer)
    Checkin.create(bar: bar8, beer: beer)
    Checkin.create(bar: bar9, beer: beer)

    visit beer_path(beer)

    expect(page).to have_content(' Últimos checkins: ')
    expect(page).to have_css('li', text: bar0.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar1.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar2.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar3.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar4.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar5.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar6.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar7.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar8.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
    expect(page).to have_css('li', text: bar9.name.to_s)
    expect(page).to have_css('li', text: 'menos de um minuto')
  end

  scenario 'hasn`t checkins' do
    beer = create(:beer)
    bar = create(:bar, name: 'Meu Bar')
    BarBeer.create(bar: bar, beer: beer)

    visit beer_path(beer)

    expect(page).to have_content('Seja o primeiro a fazer esse checkin')
  end
end
